# Generated by Django 5.2.5 on 2025-08-13 22:12

import django.core.validators
import django.db.models.deletion
import documentos.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('cobradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('boleta', 'Boleta'), ('nota_pedido', 'Nota de Pedido'), ('nota_venta', 'Nota de Venta'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('serie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('fecha_emision', models.DateTimeField(default=documentos.models.localtime_peru, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de Vencimiento')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Pagado')),
                ('monto_devolucion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Devolución')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('cobrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cobradores.cobrador', verbose_name='Cobrador')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
