# Generated by Django 5.2.5 on 2025-09-11 02:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_empresaconfig'),
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Repartidor')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-fecha', 'repartidor__username'],
                'unique_together': {('fecha', 'repartidor')},
            },
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Pedido')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cobrado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cobrado')),
                ('medio_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('yape', 'Yape / Plin'), ('transferencia', 'Transferencia'), ('deposito', 'Depósito Bancario'), ('credito', 'Crédito'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Medio de Pago')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='documentos.despacho')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.documento')),
            ],
            options={
                'verbose_name': 'Detalle de Despacho',
                'verbose_name_plural': 'Detalles de Despacho',
            },
        ),
    ]
