# Generated by Django 5.2.5 on 2025-09-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
