# Generated by Django 5.2.5 on 2025-09-08 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobradores', '0002_cobrador_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrador',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema asociado a este cobrador (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrador', to=settings.AUTH_USER_MODEL),
        ),
    ]
