# Generated by Django 5.2.5 on 2025-08-14 03:30

import cobros.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobradores', '0001_initial'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Pagado (S/)')),
                ('fecha', models.DateTimeField(default=cobros.models.localtime_peru, verbose_name='Fecha del Pago')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobradores.cobrador', verbose_name='Cobrador')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.documento', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'ordering': ['-fecha'],
            },
        ),
    ]
