# Generated by Django 5.2.5 on 2025-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='referencia',
            field=models.CharField(blank=True, help_text='Número de recibo, transferencia, depósito, etc.', max_length=50, null=True, verbose_name='Referencia / N° Operación'),
        ),
    ]
