# Generated by Django 5.2.5 on 2025-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_cobro_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='notas',
            field=models.TextField(blank=True, help_text='Información extra sobre el pago (opcional)', null=True, verbose_name='Notas Adicionales'),
        ),
    ]
