# Generated by Django 5.2.5 on 2025-08-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_cobro_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='notas',
            field=models.CharField(blank=True, help_text='Información extra sobre el pago (opcional). Máx. 60 caracteres.', max_length=60, null=True, verbose_name='Notas Adicionales'),
        ),
    ]
