# Generated by Django 5.2.5 on 2025-09-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0004_alter_cobro_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='correlativo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
