# Generated by Django 5.2.5 on 2025-09-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0005_cobro_correlativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Fecha del primer día del mes, ej: 2025-09-01')),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Mensual',
                'verbose_name_plural': 'Metas Mensuales',
                'unique_together': {('mes',)},
            },
        ),
    ]
