# Generated by Django 5.2.5 on 2025-09-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0006_metamensual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metamensual',
            options={},
        ),
        migrations.AlterField(
            model_name='metamensual',
            name='mes',
            field=models.DateField(help_text='Primer día del mes, ej: 2025-09-01'),
        ),
    ]
