# Generated by Django 5.2.5 on 2025-09-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0007_alter_metamensual_options_alter_metamensual_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('deposito', 'Depósito'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de Pago'),
        ),
    ]
