# Generated by Django 5.2.5 on 2025-09-07 01:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobradores', '0002_cobrador_activo'),
        ('cobros', '0008_cobro_tipo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Día que se cierra la planilla')),
                ('total_cobrado', models.DecimalField(decimal_places=2, help_text='Total de cobros del día', max_digits=12)),
                ('total_depositado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, help_text='Notas generales del cierre', null=True)),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobradores.cobrador')),
            ],
            options={
                'verbose_name': 'Planilla de Cierre',
                'verbose_name_plural': 'Planillas de Cierre',
                'ordering': ['-fecha'],
                'unique_together': {('cobrador', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='DepositoParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobros.planillacierre')),
            ],
            options={
                'verbose_name': 'Depósito Parcial',
                'verbose_name_plural': 'Depósitos Parciales',
                'ordering': ['-fecha'],
            },
        ),
    ]
