# Generated by Django 5.2.5 on 2025-09-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0009_planillacierre_depositoparcial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaCorrelativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre único de la secuencia (ej: 'cobro')", max_length=50, unique=True)),
                ('ultimo_correlativo', models.IntegerField(default=0, help_text='Último número de correlativo usado')),
                ('año', models.IntegerField(help_text='Año al que pertenece la secuencia')),
            ],
            options={
                'verbose_name': 'Secuencia de Correlativo',
                'verbose_name_plural': 'Secuencias de Correlativos',
                'unique_together': {('nombre', 'año')},
            },
        ),
    ]
