# Generated by Django 5.2.5 on 2025-09-16 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0010_secuenciacorrelativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que registró este pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
