# Generated by Django 5.2.5 on 2025-09-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobros", "0011_cobro_usuario_registro"),
    ]

    operations = [
        migrations.AddField(
            model_name="planillacierre",
            name="actualizado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
