# Generated by Django 4.2 on 2026-01-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0012_planillacierre_actualizado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuenciacorrelativo',
            name='nombre',
            field=models.CharField(help_text="Nombre único de la secuencia (ej: 'cobro')", max_length=50),
        ),
    ]
