# Generated by Django 5.2.5 on 2025-08-20 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('cobradores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('cliente', 'Cliente'), ('documento', 'Documento'), ('cobro', 'Cobro'), ('devolucion', 'Devolución'), ('reporte', 'Reporte'), ('otro', 'Otro')], max_length=20)),
                ('accion', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cobrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cobradores.cobrador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
