# Generated by Django 5.2.5 on 2025-08-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='notas',
            field=models.CharField(blank=True, help_text='Información extra sobre la devolución (opcional). Máx. 60 caracteres.', max_length=60, null=True, verbose_name='Notas Adicionales'),
        ),
    ]
